[tool.poetry]
name = "elect_store"
version = "0.0.1"
description = ""
authors = [ "Kn1gh16 Danchenko0@mail.ru"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"